name: Format

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Rust
        run: |
          rustup toolchain install stable --profile default --no-self-update
          rustup default stable
          echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
          echo CARGO_TERM_COLOR=always >> $GITHUB_ENV        

      - name: Check Format
        run: cargo fmt -- --check
